

import type {Metadata} from "next";
import {Providers} from "@/app/providers";
import {Toaster} from "sonner";
import Header from "@/components/ui/header/Header";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang='en'>
        <body>
        <Providers>

            {children}
            <Toaster
                theme='dark'
                position='bottom-right'
                duration={1500}
            />
        </Providers>
        </body>
        </html>
    );
}
